name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code  #####Baja el codigo al agente que est√° corriendo esto
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1   ###Setea un build? Notenemonidea de que hace

      - name: Login to Github Packages
        uses: docker/login-action@v1        ####Se loguea al contaainer registry con:
        with:
          registry: ghcr.io
          username: ${{ github.actor }}     ####Mi username
          password: ${{ secrets.CONTAINER_REGISTRY }}   ####Mi PAT que acabo de crear
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2             ####Aca buildea
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./app
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/ezequielandrush/k8s_thw/testapp:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
